- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/Personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    #- include: tasks/ssh.yml
    #- include: tasks/git.yml    
    #- include: tasks/brave.yml
    #- include: tasks/chrome.yml
    - include: tasks/personal_projects.yml
    #- include: tasks/node.yml
    - include: tasks/npm_packages.yml
    #- include: tasks/zsh.yml
    #- include: tasks/vscode.yml
    #- include: tasks/slack-setup.yml
