- hosts: localhost
  vars:
    source_ssh_config: "./.ssh/config"
    dest_ssh_config: "{{ lookup('env', 'HOME') }}/.ssh"
    source_personal_key: "./.ssh/id_rsa"
    dest_personal_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    source_runcode_key: "./.ssh/id_ed25519_runcode"
    dest_runcode_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_runcode"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    runcode: "{{ lookup('env', 'HOME') }}/runcode"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git.yml    
    - import_tasks: tasks/brave.yml
    - import_tasks: tasks/chrome.yml
    - import_tasks: tasks/personal_projects.yml
    - import_tasks: tasks/runcode_projects.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/npm_packages.yml
    - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/go.yml
    - import_tasks: tasks/fonts.yml
