- name: Chrome Browser package download
  become: true
  shell: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  tags:
    - chrome
    - install

- name: Install chrome
  become: true
  shell: sudo dpkg -i google-chrome-stable_current_amd64.deb
  tags:
    - chrome
    - install
    
- name: Remove install chrome package
  become: true
  shell: rm -rf google-chrome-stable_current_amd64.deb
  tags:
    - chrome
    - install
