# AR-APP-WEB PROJECT

- name: ar-app-web exists
  stat:
    path: "{{ falagan_software }}/projects/ar-app-web"
  register: arAppWeb
  tags:
    - install
    - ar-app-web
    - falagan_software-project

- name: falagan_software project ar-app-web
  git:
    repo: "git@github.com-falagansoftware:falagansoftware/ar-app-web.git"
    dest: "{{ falagan_software }}/projects/ar-app-web"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - ar-app-web
    - falagan_software-project
  when: arAppWeb.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ falagan_software }}/projects/ar-app-web"
    name: user.email
    scope: local
    value: "falagansoftware@gmail.com"
  tags:
  - git-falagan

- name: Git setup name
  git_config:
    repo: "{{ falagan_software }}/projects/ar-app-web"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-falagan

# AR-SERVICE-WEB PROJECT

- name: ar-service-api exists
  stat:
    path: "{{ falagan_software }}/projects/ar-service-api"
  register: arServiceApi
  tags:
    - install
    - ar-service-api
    - falagan_software-project

- name: falagan_software project ar-service-api
  git:
    repo: "git@github.com-falagansoftware:falagansoftware/ar-service-api.git"
    dest: "{{ falagan_software }}/projects/ar-service-api"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - ar-service-api
    - falagan_software-project
  when: arServiceApi.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ falagan_software }}/projects/ar-service-api"
    name: user.email
    scope: local
    value: "falagansoftware@gmail.com"
  tags:
  - git-falagan

- name: Git setup name
  git_config:
    repo: "{{ falagan_software }}/projects/ar-service-api"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-falagan

# FALAGAN_PLAN PROJECT

- name: falagan_plan exists
  stat:
    path: "{{ falagan_software }}/projects/falagan_plan"
  register: falaganPlan
  tags:
    - install
    - falagan_plan
    - falagan_software-project

- name: falagan_software project falagan_plan
  git:
    repo: "git@github.com-falagansoftware:falagansoftware/falagan_plan.git"
    dest: "{{ falagan_software }}/projects/falagan_plan"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - falagan_plan
    - falagan_software-project
  when: falaganPlan.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ falagan_software }}/projects/falagan_plan"
    name: user.email
    scope: local
    value: "falagansoftware@gmail.com"
  tags:
  - git-falagan

- name: Git setup name
  git_config:
    repo: "{{ falagan_software }}/projects/falagan_plan"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-falagan

  #AUTO-REPAIR PROJECT

- name: auto-repair exists
  stat:
    path: "{{ falagan_software }}/projects/auto-repair"
  register: autoRepair
  tags:
    - install
    - auto-repair
    - falagan_software-project

- name: falagan_software project auto-repair
  git:
    repo: "git@github.com-falagansoftware:falagansoftware/auto-repair.git"
    dest: "{{ falagan_software }}/projects/auto-repair"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - auto-repair
    - falagan_software-project
  when: autoRepair.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ falagan_software }}/projects/auto-repair"
    name: user.email
    scope: local
    value: "falagansoftware@gmail.com"
  tags:
  - git-falagan

- name: Git setup name
  git_config:
    repo: "{{ falagan_software }}/projects/auto-repair"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-falagan