- name: ar-app-web exists
  stat:
    path: "{{ personal }}/Projects/ar-app-web"
  register: arAppWeb
  tags:
    - install
    - dotfiles
    - ar-app-web
    - personal-project
    
- name: Personal Project ar-app-web
  git:
    repo: 'git@github.com:Falagan/ar-app-web.git'
    dest: "{{ personal }}/Projects/ar-app-web"
    clone: yes
    update: yes
  tags:
    - install
    - dotfiles
    - ar-app-web
    - personal-project
  when: arAppWeb.stat.exists == False
  
- name: ar-service-api exists
  stat:
    path: "{{ personal }}/Projects/ar-service-api"
  register: arServiceApi
  tags:
    - install
    - dotfiles
    - ar-service-api
    - personal-project
    
- name: Personal Project ar-service-api
  git:
    repo: 'git@github.com:Falagan/ar-service-api.git'
    dest: "{{ personal }}/Projects/ar-service-api"
    clone: yes
    update: yes
  tags:
    - install
    - dotfiles
    - ar-service-api
    - personal-project
  when: arServiceApi.stat.exists == False
