#CAREER-APP PROJECT

- name: career-app exists
  stat:
    path: "{{ personal }}/projects/career-app"
  register: careerApp
  tags:
    - install
    - career-app
    - personal-project
    
- name: personal project career-app
  git:
    repo: 'git@github.com:Falagan/career-app.git'
    dest: "{{ personal }}/projects/career-app"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - career-app
    - personal-project
  when: careerApp.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ personal }}/projects/career-app"
    name: user.email
    scope: local
    value: "ep.falagan@gmail.com"
  tags:
  - git-personal

- name: Git setup name
  git_config:
    repo: "{{ personal }}/projects/career-app"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-personal

#CAREER-API PROJECT

- name: career-api exists
  stat:
    path: "{{ personal }}/projects/career-api"
  register: careerApi
  tags:
    - install
    - career-api
    - personal-project

- name: personal project career-api
  git:
    repo: 'git@github.com:Falagan/career-api.git'
    dest: "{{ personal }}/projects/career-api"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - career-api
    - personal-project
  when: careerApi.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ personal }}/projects/career-api"
    name: user.email
    scope: local
    value: "ep.falagan@gmail.com"
  tags:
  - git-personal

- name: Git setup name
  git_config:
    repo: "{{ personal }}/projects/career-api"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-personal

#GO-HTMX PROJECT

- name: go-htmx exists
  stat:
    path: "{{ personal }}/projects/go-htmx"
  register: goHtmx
  tags:
    - install
    - go-htmx
    - personal-project
    
- name: personal project go-htmx
  git:
    repo: 'git@github.com:Falagan/go-htmx.git'
    dest: "{{ personal }}/projects/go-htmx"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - go-htmx
    - personal-project
  when: goHtmx.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ personal }}/projects/go-htmx"
    name: user.email
    scope: local
    value: "ep.falagan@gmail.com"
  tags:
  - git-personal

- name: Git setup name
  git_config:
    repo: "{{ personal }}/projects/go-htmx"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-personal

#REPORT-SIL PROJECT

- name: report-sil exists
  stat:
    path: "{{ personal }}/projects/report-sil"
  register: reportSil
  tags:
    - install
    - report-sil
    - personal-project
    
- name: personal project report-sil
  git:
    repo: 'git@github.com:Falagan/report-sil.git'
    dest: "{{ personal }}/projects/report-sil"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - report-sil
    - personal-project
  when: reportSil.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ personal }}/projects/report-sil"
    name: user.email
    scope: local
    value: "ep.falagan@gmail.com"
  tags:
  - git-personal

  # AR-APP-WEB PROJECT

- name: ar-app-web exists
  stat:
    path: "{{ personal }}/projects/ar-app-web"
  register: arAppWeb
  tags:
    - install
    - ar-app-web
    - personal-project

- name: personal project ar-app-web
  git:
    repo: "git@github.com:Falagan/ar-app-web.git"
    dest: "{{ personal }}/projects/ar-app-web"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - ar-app-web
    - personal-project
  when: arAppWeb.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ personal }}/projects/ar-app-web"
    name: user.email
    scope: local
    value: "ep.falagan@gmail.com"
  tags:
  - git-falagan

- name: Git setup name
  git_config:
    repo: "{{ personal }}/projects/ar-app-web"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-falagan

# AR-SERVICE-WEB PROJECT

- name: ar-service-api exists
  stat:
    path: "{{ personal }}/projects/ar-service-api"
  register: arServiceApi
  tags:
    - install
    - ar-service-api
    - personal-project

- name: personal project ar-service-api
  git:
    repo: "git@github.com:Falagan/ar-service-api.git"
    dest: "{{ personal }}/projects/ar-service-api"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - ar-service-api
    - personal-project
  when: arServiceApi.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ personal }}/projects/ar-service-api"
    name: user.email
    scope: local
    value: "ep.falagan@gmail.com"
  tags:
  - git-falagan

- name: Git setup name
  git_config:
    repo: "{{ personal }}/projects/ar-service-api"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-falagan

# FALAGAN_PLAN PROJECT

- name: falagan_plan exists
  stat:
    path: "{{ personal }}/projects/falagan_plan"
  register: falaganPlan
  tags:
    - install
    - falagan_plan
    - personal-project

- name: personal project falagan_plan
  git:
    repo: "git@github.com:Falagan/falagan_plan.git"
    dest: "{{ personal }}/projects/falagan_plan"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - falagan_plan
    - personal-project
  when: falaganPlan.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ personal }}/projects/falagan_plan"
    name: user.email
    scope: local
    value: "ep.falagan@gmail.com"
  tags:
  - git-falagan

- name: Git setup name
  git_config:
    repo: "{{ personal }}/projects/falagan_plan"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-falagan

  #AUTO-REPAIR PROJECT

- name: auto-repair exists
  stat:
    path: "{{ personal }}/projects/auto-repair"
  register: autoRepair
  tags:
    - install
    - auto-repair
    - personal-project

- name: personal project auto-repair
  git:
    repo: "git@github.com:Falagan/auto-repair.git"
    dest: "{{ personal }}/projects/auto-repair"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - auto-repair
    - personal-project
  when: autoRepair.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ personal }}/projects/auto-repair"
    name: user.email
    scope: local
    value: "ep.falagan@gmail.com"
  tags:
  - git-falagan

- name: Git setup name
  git_config:
    repo: "{{ personal }}/projects/auto-repair"
    name: user.name
    scope: local
    value: "Eloy Perez"
  tags:
  - git-falagan

#KNOWLEDGE PROJECT

- name: knowledge exists
  stat:
    path: "{{ personal }}/projects/knowledge"
  register: knowledge
  tags:
    - install
    - knowledge
    - personal-project
    
- name: personal project knowledge
  git:
    repo: 'git@github.com:Falagan/knowledge.git'
    dest: "{{ personal }}/projects/knowledge"
    clone: yes
    update: yes
    accept_hostkey: yes
    force: yes
  tags:
    - install
    - knowledge
    - personal-project
  when: knowledge.stat.exists == False

- name: Git setup email
  git_config:
    repo: "{{ personal }}/projects/knowledge"
    name: user.email
    scope: local
    value: "ep@runcode.sh"
  tags:
  - git-personal