- name: career-app exists
  stat:
    path: "{{ personal }}/Projects/career-app"
  register: careerApp
  tags:
    - install
    - dotfiles
    - career-app
    - personal-project
    
- name: personal Project career-app
  git:
    repo: 'git@github.com:Falagan/career-app.git'
    dest: "{{ personal }}/Projects/career-app"
    clone: yes
    update: yes
  tags:
    - install
    - dotfiles
    - career-app
    - personal-project
  when: careerApp.stat.exists == False
  
- name: career-api exists
  stat:
    path: "{{ personal }}/Projects/career-api"
  register: careerApi
  tags:
    - install
    - dotfiles
    - career-api
    - personal-project
    
- name: personal Project career-api
  git:
    repo: 'git@github.com:Falagan/career-api.git'
    dest: "{{ personal }}/Projects/career-api"
    clone: yes
    update: yes
  tags:
    - install
    - dotfiles
    - career-api
    - personal-project
  when: careerApi.stat.exists == False
