# SSH CONFIG
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_ssh_config | dirname }}"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh
- name: Install ssh config
  copy:
    src: "{{ source_ssh_config }}"
    dest: "{{ dest_ssh_config }}"
    mode: 0600
  tags:
    - install
    - ssh
- name: set know hosts
  become: true
  shell: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  tags:
    - install
    - ssh
# PERSONAL SSH KEYS
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_personal_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh
- name: Install personal ssh key
  copy:
    src: "{{ source_personal_key }}"
    dest: "{{ dest_personal_key }}"
    mode: 0600
  tags:
    - install
    - ssh
- name: Install personal ssh key public
  copy:
    src: "{{ source_personal_key }}.pub"
    dest: "{{ dest_personal_key }}.pub"
    mode: 0644
  tags:
    - install
    - ssh
#FALAGAN SSH KEYS
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_falagan_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh
- name: Install falagan ssh key
  copy:
    src: "{{ source_falagan_key }}"
    dest: "{{ dest_falagan_key }}"
    mode: 0600
  tags:
    - install
    - ssh
- name: Install falagan ssh key public
  copy:
    src: "{{ source_falagan_key }}.pub"
    dest: "{{ dest_falagan_key }}.pub"
    mode: 0644
  tags:
    - install
    - ssh
# SET den-env repository url to use SSH
- name: Set dev-env repo url to use ssh\
  become: true
  shell: cd ~/personal/projects/dev-env && git remote set-url origin git@github.com:Falagan/dev-env.git
  tags:
    - install
    - ssh
#- name: Set authorized key took from file
  #authorized_key:
    #user: "{{ lookup('env', 'USER') }}"
    #state: present
    #key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  #with_fileglob:
  #- "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
