# SSH CONFIG
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_personal_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh config
  copy:
    src: "{{ source_ssh_config }}"
    dest: "{{ dest_ssh_config }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
# PERSONAL SSH KEYS
- name: Install personal ssh key
  copy:
    src: "{{ source_personal_key }}"
    dest: "{{ dest_personal_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install personal ssh key public
  copy:
    src: "{{ source_personal_key }}.pub"
    dest: "{{ dest_personal_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
#RUNCODE SSH KEYS
- name: Install runcode ssh key
  copy:
    src: "{{ source_runcode_key }}"
    dest: "{{ dest_runcode_key }}"
    mode: 0600
  tags:
    - dotfiles
    - install
    - ssh
- name: Install runcode ssh key public
  copy:
    src: "{{ source_runcode_key }}.pub"
    dest: "{{ dest_runcode_key }}.pub"
    mode: 0644
  tags:
    - dotfiles
    - install
    - ssh
